# Pantalla
WIDTH = 800
HEIGHT = 600
WIDTH_MID = WIDTH // 2
HEIGHT_MID = HEIGHT // 2
WIDTH_THIRD = WIDTH // 3
HEIGHT_THIRD = HEIGHT // 3
WIDTH_FOURTH = WIDTH // 4
HEIGHT_FOURTH = HEIGHT // 4
SCREEN_SIZE = (WIDTH, HEIGHT)
SCREEN_CENTER = (WIDTH_MID, HEIGHT_MID)
ORIGIN = (0, 0)
SCREEN_CENTER_UP = (WIDTH_MID, HEIGHT_FOURTH)
SCREEN_CENTER_BOTTOM = (WIDTH_MID, HEIGHT - HEIGHT_FOURTH)

TITULO_POS = (WIDTH_MID, HEIGHT_FOURTH - 50)
JUGAR_POS = (WIDTH_MID, HEIGHT_MID - 50)
PUNTAJES_POS = (WIDTH_MID, HEIGHT_MID + 25)
OPCIONES_POS = (WIDTH_MID, HEIGHT_MID + 100)
SALIR_POS = (WIDTH_MID, HEIGHT_MID + 175)
VOL_SON_POS = (WIDTH_THIRD, HEIGHT_MID - 50)
VOL_MUSIC_POS = (WIDTH_THIRD, HEIGHT_MID + 25)
X_MENOS = 25
X_MAS = 85
MENOS_SONIDO_POS = (WIDTH_MID + X_MENOS, HEIGHT_MID - 55)
MAS_SONIDO_POS = (WIDTH_MID + X_MAS + 5, HEIGHT_MID - 55)
MENOS_MUSIC_POS = (WIDTH_MID + X_MENOS, HEIGHT_MID + 25)
MAS_MUSIC_POS = (WIDTH_MID + X_MAS + 5, HEIGHT_MID + 25)

# Datos
FPS = 30
FUENTE_TITULO = 72
FUENTEO_PCIONES = 50
FUENTE_PUNTAJES = 25

MENU_PR = "A"
MENU_PU = "B"
MENU_OP = "C"

# RGB

COLOR_CUSTOM = (255,200,130)
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
BLACK = (0,0,0)
WHITE = (255,255,255)
ORANGE = (255,166,0)
VIOLET = (128,0,128)
CIAN = (0,255,255)
MAGENTA = (255,0,255)
YELLOW = (255,255,0)

colors = [RED,GREEN,BLUE,BLACK,WHITE,ORANGE,CIAN,MAGENTA,YELLOW]

