# Pantalla
WIDTH = 800
HEIGHT = 600
WIDTH_MID = WIDTH // 2
HEIGHT_MID = HEIGHT // 2
WIDTH_THIRD = WIDTH // 3
HEIGHT_THIRD = HEIGHT // 3
WIDTH_FOURTH = WIDTH // 4
HEIGHT_FOURTH = HEIGHT // 4
SCREEN_SIZE = (WIDTH, HEIGHT)
SCREEN_CENTER = (WIDTH_MID, HEIGHT_MID)
ORIGIN = (0, 0)
SCREEN_CENTER_UP = (WIDTH_MID, HEIGHT_FOURTH)
SCREEN_CENTER_BOTTOM = (WIDTH_MID, HEIGHT - HEIGHT_FOURTH)

TITULO_POS = (WIDTH_MID, HEIGHT_FOURTH - 50)
JUGAR_POS = (WIDTH_MID, HEIGHT_MID - 50)
PUNTAJES_POS = (WIDTH_MID, HEIGHT_MID + 25)
OPCIONES_POS = (WIDTH_MID, HEIGHT_MID + 100)
SALIR_POS = (WIDTH_MID, HEIGHT_MID + 200)
VOL_SON_POS = (WIDTH_FOURTH, HEIGHT_MID - 50)
VOL_SON_NUM_POS = (WIDTH_MID + 55, HEIGHT_MID - 50)
VOL_MUSIC_POS = (WIDTH_FOURTH, HEIGHT_MID + 25)
VOL_MUSIC_NUM_POS = (WIDTH_MID + 55, HEIGHT_MID + 25)
X_MENOS = 25
X_MAS = 85
MENOS_SONIDO_POS = (WIDTH_MID + X_MENOS, HEIGHT_MID - 55)
MAS_SONIDO_POS = (WIDTH_MID + X_MAS + 5, HEIGHT_MID - 55)
MENOS_MUSIC_POS = (WIDTH_MID + X_MENOS, HEIGHT_MID + 25)
MAS_MUSIC_POS = (WIDTH_MID + X_MAS + 5, HEIGHT_MID + 25)
SCORE_POS = (WIDTH - 100, HEIGHT - 25)
MESSAGE_STAR_POS = (WIDTH_MID, HEIGHT - 50)
GUARDAR_POS = (WIDTH_MID, HEIGHT_MID + 125)
MUTE_POS = (50, HEIGHT - 50)



# Datos pantalla
FPS = 120
FUENTE_TITULO = 72
FUENTEO_PCIONES = 50
FUENTE_PUNTAJES = 25
FUENTE_GAME = 36
MENU_PR = "A"
MENU_PU = "B"
MENU_OP = "C"
MENU_JUGAR = "D"

# rects
LASER_WIDTH = 6
LASER_HEIGHT = 12
CARD_SPEED = 5
RECT_WIDTH = 200
RECT_HEIGHT = 100
LIVE_WIDTH = 50
LIVE_HEIGHT = 50
live_left = 50
LIVE_TOP = 50
vida_x = 50
vida_y = 50

# Players
player_w = 50
player_h = 50
move_left = False
move_right = False
move_up = False
move_down = False
move_left_a = False
speed_player_x = 1
speed_player_y = 1
PLAYER_WIDTH = 150
PLAYER_HEIGHT = 190
U = 8
D = 2
R = 6
L = 4
UR = 9
DR = 3
DL = 1
UL = 7
TUPLE_DIR = (0,1,2,3,4,6,7,8,9)
QUIETO = 0
MOVE_LADO = 1
MOVE_DOWN = 2
P_SACAR_AMARILLA = 3
P_SACAR_ROJA = 4
P_MOVE_UP = 5
P_GAME_OVER = 6
J_MOVE_UP = 3



# Sonido
volumen_sonido = 1
volumen_musica = 1
TUPLE_VOLUMEN = (0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0)

# RGB

COLOR_CUSTOM = (255,200,130)
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
BLACK = (0,0,0)
WHITE = (255,255,255)
ORANGE = (255,166,0)
VIOLET = (128,0,128)
CIAN = (0,255,255)
MAGENTA = (255,0,255)
YELLOW = (255,255,0)

colors = (RED,GREEN,BLUE,BLACK,WHITE,ORANGE,CIAN,MAGENTA,YELLOW)
TUPLA_COLOR_TARJETA = (YELLOW,RED)
